#!/bin/bash
# pre-commit hook for OD projects
# will run php code sniff before committing to make sure code conforms to standard

OUTPUT=$(./vendor/bin/phpcs --standard=psr12 app/ -n)
RETVAL=$?

if [ $RETVAL -ne 0 ]; then
    echo "$OUTPUT"
fi

exit $RETVAL